### ISSUE TITLE
Product images don't load sometimes

### ISSUE THREAD

**Issue by ifvictr** [hackclub/shop#14]

**Comment by lachlanjc** [comment]
Details on this?

**Comment by ifvictr** [comment]
Not much, but the requests for the images return with a `200`. However, the images don't appear after the loaders disappear.

**Comment by ifvictr** [comment]
The problem _could_ be caused by react-image. Let's try replacing it with DS's Image component and see if it's fixed?

**Comment by merelinguist** [comment]
I think this is resolved with our new approach to images.
